// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
// Load .env.local first (where Supabase DATABASE_URL/DIRECT_URL live), then .env.
// Plain `dotenv/config` only reads .env — the Prisma CLI would otherwise miss the
// Supabase connection strings that Next.js itself reads from .env.local at runtime.
// dotenv does not override already-set keys, so .env.local takes precedence.
import { config } from "dotenv";
config({ path: [".env.local", ".env"] });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Prisma 7: seed 커맨드는 여기서 배선 (package.json#prisma.seed 폐지).
    // seed.ts 는 TS + generated client import 라 tsx 러너로 실행.
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // CLI(migrate/introspect)는 direct connection(포트 5432)을 써야 한다 —
    // Supabase pgBouncer(6543)는 DDL/advisory lock 미지원이므로 DIRECT_URL 우선.
    // 런타임 쿼리는 db.ts 의 PrismaPg 어댑터가 DATABASE_URL(pooler 6543)로 별도 연결.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
